### ISSUE TITLE
Cannot install on ubuntu

### ISSUE THREAD

**Issue by mokytis** [beeware/podium#11]
I tried to install podium via `pip install podium` in a python3 virtual environment
When pip installing I get
  Collecting podium
  Could not find a version that satisfies the requirement podium (from versions: )
  No matching distribution found for podium

I am going to try installing from source code

**Comment by luke-spademan** [comment]
after flowing instructions at readthedocs, I ended up with the error:
ValueError: Library 'Foundation' not found

pip install Foundation does not help

**Comment by bittner** [comment]
Effectively, you need to follow the [Briefcase tutorial](https://briefcase.readthedocs.io/en/latest/tutorial/getting-started.html) to install (and run) Podium, when you try to install from source, e.g.

```console
$ pip install briefcase
$ pip install --pre toga
$ python setup.py linux -s
```

This will create a `linux` folder with a `Podium` executable. The `-s` in the last command above should run that executable (which it doesn't seem to, on my machine at least, for the moment).

**Comment by freakboy3742** [comment]
This has now been resolved; Podium is available as an AppImage for Linux, and can be run from source.
