### ISSUE TITLE
Cannot open using `open <deck>.podium`

### ISSUE THREAD

**Issue by glasnt** [beeware/podium#17]
## Expected behaviour

In a terminal on macOS, executing `open <deck>.podium` should open the deck in podium

## Actual behaviour

Invoking the command opens podium in my taskbar, but doesn't open the deck. 

I can then navigate to podium, which invokes a file selector window, where I can then open my deck. 

## Local system

macOS High Sierra, iterm2

**Comment by freakboy3742** [comment]
Confirmed. 

For the record: there's 5 ways you should be able to open a slide deck:

1. Open Podium from finder/launchpad, select document
2. Double click on a podium deck in finder
3. Drag a podium deck onto Podium in the taskbar
4. `open <deck>.podium` from the command line
5. `podium <deck.podium>` from the command line, inside a virtual environment.

The process of opening documents is a little complex. It's (unfortunately) not as simple as just using sys.argv; it relies on the Cocoa NSDocument interface that was recently abstracted behind DocumentApp.

**Comment by freakboy3742** [comment]
Resolved by #686
