### ISSUE TITLE
Package Error: Unable to clone application template because of wrong path

### ISSUE THREAD

**Issue by paddy-exe** [beeware/podium#52]
When trying to package the app, this error pops up:
% briefcase package

[podium] Generating application template...
Using app template: /Users/rkm/projects/beeware/templates/briefcase-macOS-app-template
Unable to clone application template; is the template path '/Users/rkm/projects/beeware/templates/briefcase-macOS-app-template' correct?

**To Reproduce**
1. Follow the instructions for the contribution
2. briefcase package in terminal
3. See the error

**Expected behavior**
Packaging successful

**Environment:**
 - Operating System: OSX 10.15.6
 - Python version: 3.7
 - Software versions:
   - Briefcase: pre-release
   - Toga: pre-release

**Additional context**
I suppose the directory for the app template needs to be changed so that others can package it as well

**Comment by freakboy3742** [comment]
Thanks for the report! Looks like I've left a stray local configuration item in the pyproject.toml; fix incoming shortly.
